version: "3"
services:
  client1:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - app-network
  client2:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    networks:
      - app-network
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - app-network
  database:
    build: ./database
    ports:
      - "27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
